name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - name: Build for simulator
      run: |
        xcodebuild clean build \
        -project Guess-The-flag-main/Guess-The-Flag/Guess-The-Flag.xcodeproj \
        -scheme Guess-The-Flag \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
