name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Show current folder and files
       run: |
          echo "Current Directory:"
          pwd
          echo "Files and Folders:"
          ls -la
          echo "Recursive Listing:"
          ls -R

     - name: List Xcode schemes
       run: |
         cd Guess-The-Flag
         xcodebuild -list -project Guess-The-Flag.xcodeproj
     - name: Clean DerivedData
       run: |
         rm -rf ~/Library/Developer/Xcode/DerivedData  
         
     - name: Build for simulator
       run: |
        cd Guess-The-Flag
        xcodebuild clean build \
        -project Guess-The-Flag.xcodeproj \
        -scheme Guess-The-Flag \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGN_IDENTITY="" \
        EXCLUDED_ARCHS=arm64 \
        ONLY_ACTIVE_ARCH=YES
