# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Show current folder and files
       run: |
          echo "Current Directory:"
          pwd
          echo "Files and Folders:"
          ls -la
          echo "Recursive Listing:"
          ls -R

     - name: List Xcode schemes
       run: |
         cd Guess-The-Flag
         xcodebuild -list -project Guess-The-Flag.xcodeproj
     - name: Build for simulator
       run: |
        cd Guess-The-Flag
        xcodebuild clean build \
        -project Guess-The-Flag.xcodeproj \
         xcodebuild clean build \
        -scheme Guess-The-Flag \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO \
        CODE_SIGN_IDENTITY="" \
        EXCLUDED_ARCHS=arm64
