# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: List all files
      run: |
        ls -R
    - name: Build for simulator
      run: |
        xcodebuild clean build \
        -project Guess-The-Flag.xcodeproj \
        -scheme Guess-The-flag \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 14' \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
